### ISSUE TITLE
Building on Ubuntu 18.04

### ISSUE THREAD

**Issue by aolney** [vuori/linux-minidisc#1]
Had to do a few things extra; perhaps the README needs to be updated?

sudo apt-get install libgcrypt20-dev libglib2.0-dev libusb-1.0-0-dev qt4-qmake **libid3tag0-dev libmad0-dev**
qmake **-qt=qt4** CONFIG+=without_mad CONFIG+=without_gui

**Comment by vuori** [comment]
Thanks, fixed.
